# Docker Compose configuration for development and production

version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - uploads_data:/app/app/uploads
      - plots_data:/app/app/static/plots
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Production configuration
  web-prod:
    build: .
    ports:
      - "80:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    volumes:
      - uploads_data:/app/app/uploads
      - plots_data:/app/app/static/plots
    restart: unless-stopped
    profiles:
      - production

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web-prod
    restart: unless-stopped
    profiles:
      - production

volumes:
  uploads_data:
  plots_data:
